export const navList = [
    { 
        path: "index", 
        name: 'Home', 
        icon: 'el-home',
        path: "/",  
    },
    { path: "/triangle", name: 'Triangle', icon: 'el-home' },
    { path: "/triangle", name: 'Triangle', icon: 'el-home' },
    { path: "/triangle", name: 'Triangle', icon: 'el-home' },
    { path: "/triangle", name: 'Triangle', icon: 'el-home' },
    { path: "/triangle", name: 'Triangle', icon: 'el-home' },
    { path: "/triangle", name: 'Triangle', icon: 'el-home' },
    { path: "/triangle", name: 'Triangle', icon: 'el-home' },
    { path: "/triangle", name: 'Triangle', icon: 'el-home' },
    { path: "/triangle", name: 'Triangle', icon: 'el-home' },
    { path: "/triangle", name: 'Triangle', icon: 'el-home' },
    { path: "/triangle", name: 'Triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
    { path: "/triangle", name: 'triangle', icon: 'el-home' },
]